<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Info Pets</title>
    <meta charset="utf-8">
    <!--Fichiers CSS-->
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/erreur_acces.css">
    <!--Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0b1009deec.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
    <p class="msg_erreur_acces"><?php if(isset($msg)&&$msg!=''){echo $msg;} ?></p>
    <img src="img/dog.jpg"/>
    <nav class="navig">
    <?php
    if (!isset($_SESSION['id_user'])){
    echo"<a href='inscription.php' class='inscrip'>Inscription</a>";
    echo"<a href='select_user.php' value='Connexion' name='connexion' class='connex' id='connexion'>Connexion</a>";
    }
?>
    </nav> 
</body>