<div>
            <main>
            <h2 class="titre-page"><i class="fas fa-paw"></i>Fiche informatif de votre animal<i class="fas fa-paw"></i></h2>
            <h3 class="race" id="race">Bengal (junior)</h3>
            </div>
            <img class="kitten" id="chaton" src="img/bengal_junior.jpg">
            <div class="article">
                <section>
                    <h2 class="title-left">Alimentation</h2>
                <article>
                    <img src="img/alimentation_kitten.jpg" class="right" id="alimentation">
                    <p>
                        Une alimentation spécial chaton est recommandé.
                        Les croquettes doivent contenir de la protéine de qualité, torine car non synthétisé par l'animal (la torine sert à la vue et au développement musculaire), des omégas 3 et 6 ainsi que du calcium de qualité pour que le chaton puisse se développé correctement.
                        L’alimentation humide doit aussi faire partie intégrante du repas car les chats boivent peu et sont sujet aux problèmes uriniares. 
                        Les croquettes que vous sélectionnerez ne doivent pas contenir de céréale qui ne sont pas digeste pour l’animal étant un carnivore stricte.                           
                    </p>
                </article>
            </section>
            </div>
            <div class="article">
                <section>
                    <h2 class="title-right">Toilettage</h2>
                <article>
                    <img src="img/brosse_poil_court.jpeg" class="left" id="brosse">
                    <img src="img/lotion_nettoyante.jpg" class="left">
                    <img src="img/lotion_yeux_oreille.jpg" class="left">
                    <img src="img/coupe_griffe.jpg" class="left">
                    <p>
                        Un brossage une à deux fois par semaine suffi avec une brosse souple pour ne pas blesser l’animal. 
                        Vous pouvez aussi lui nettoyer les yeux si nécessaire ainsi que les oreilles avec des produits spécifique. 
                        Si vous constaté que l’animal est sale vous pouvez le nettoyer avec une lotion que vous trouverez en animalerie.
                        Vous pouvez aussi lui couper le bout des griffes si ils sont trop longues.  Attention aux nerfs présent dans les griffes.                                                   
                    </p>
                </article>
            </section>
            </div>
            <div class="article">
                <section>
                    <h2 class="title-left">Couchage</h2>
                <article>
                    <img src="img/couchage_cat.jpg" class="right">
                    <p>
                        Il faut que celui-ci soit confortable pour que le chaton se sente en sécurité et dans un endroit calme. 
                        Le couchage peut-être ouvert ou fermer.
                        Le chaton étant un prédateur proie, il faut qu’il puisse avoir un point d'observation ainsi qu'un endroit pour se cacher et partir au moindre danger. 
                    </p>
                </article>
            </section>
        </div>
            <div class="article">
                <section>
                    <h2 class="title-right">Sellerie</h2>
                <article>
                    <img src="img/harnais.jpg" class="left">
                    <img src="img/laisse_enrouleur.jpg" class="left">
                    <p>
                        Il est préconisé si on veut promener son chaton en laisse d’utiliser un harnais plutôt qu’un collier pour qu’il se sente plus allaise dans ses déplacements. 
                        Le harnais permet de retenir son animal sans avoir de traction importante sur son cou contrairement au collier. 
                        Une laisse enrouleur est plus approprié pour une liberté de mouvement de l’animal ainsi que du propriétaire.                                               
                    </p>
                </article>
            </section>
            </div>
        </main>