<!--include header.php dans inscription.php-->
       <form method="POST" action="add_user.php">
        <h2><i class="fas fa-paw"></i>Inscription<i class="fas fa-paw"></i></h2>
        <caption><?php if(isset($msgErreurs)&&$msgErreurs!=''){echo $msgErreurs;} ?></caption>
        <div class="form-group">
        
            <h3 class="intitule">Votre nom</h3>
                <input type="text" class="form-control" name="nom" id="nom" placeholder="Entrer votre nom">
                <caption><?php if(isset($msgErreurNom)&&$msgErreurNom!=''){echo $msgErreurNom;} ?></caption>
        </div>
        <div class="form-group">
            <h3 class="intitule"> Votre prenom</h3>
                <input type="text" class="form-control" name="prenom" id="prenom" placeholder="Entrer votre prenom">
                <caption><?php if(isset($msgErreurPrenom)&&$msgErreurPrenom!=''){echo $msgErreurPrenom;} ?></caption>
        </div>
        <div class="form-group">
            <h3 class="intitule"> Votre mail</h3>
                <input type="email" class="form-control" name="email" id="email" placeholder="Entrer votre email">
                <caption><?php if(isset($msgErreurEmail)&&$msgErreurEmail!=''){echo $msgErreurEmail;} ?></caption>
        </div>
        <div class="form-group">
            <h3 class="intitule">Votre mot de passe</h3>
                <input type="password" class="form-control" name="password" id="password" placeholder="**********">
                <caption><?php if(isset($msgErreurPassword)&&$msgErreurPassword!=''){echo $msgErreurPassword;} ?></caption>
        </div>
        <input type="submit" class="valid" id="valid" name="valid" value="Valider">
        <input type="reset" class="cancel" id="cancel"  name="cancel" value="Annuler">
        </form>
<!--include footer1.php dans inscription.php-->