<form method="POST" action="select_user.php">
<input type="hidden" class="form-control" name="id_user" id="id" placeholder="Entrer votre nom">
<input type="hidden" class="form-control" name="nom" id="nom" placeholder="Entrer votre nom">

<input type="hidden" class="form-control" name="prenom" id="prenom" placeholder="Entrer votre prenom">
    <h2><i class="fas fa-paw"></i>Connexion<i class="fas fa-paw"></i></h2>
    <caption><?php if(isset($msgErreurs)&&$msgErreurs!=''){echo $msgErreurs;} ?></caption>
<div class="form-group">
    
    <h3 class="intitule">Votre mail</h3>
        <input type="email" class="form-control" name="mail" id="mail" placeholder="Entrer votre mail">
        <caption><?php if(isset($msgErreurMail)&&$msgErreurMail!=''){echo $msgErreurMail;} ?></caption>
</div>
<div class="form-group">
    <h3 class="intitule">Votre mot de passe</h3>
        <input type="password" class="form-control" name="pass" id="pass" placeholder="Entrer votre mot de passe">
        <caption><?php if(isset($msgErreurPass)&&$msgErreurPass!=''){echo $msgErreurPass;} ?></caption>
</div>
<input type="submit" class="valid" id="valid" name="valid" value="Valider">
<input type="reset" class="cancel" id="cancel"  name="cancel" value="Annuler">
</form>