     <div>
         <main>
             <h2><i class="fas fa-paw"></i>News<i class="fas fa-paw"></i></h2>
             <div class="slide">
                 <figure>
                     <img class="img" src="img/sport_canin.jpg">
                     <img class="img" src="img/techno_cat.jpg">
                     <img class="img" src="img/medecine.jpg">
                     <img class="img" src="img/insolite.jpg">
                 </figure>
             </div>
             <section>
                 <?php echo $newHtml ?>
             </section>
     </div>
     </main>
     </div>