<div>
        <main>
            <h2><i class="fas fa-paw"></i>Perte d'animaux<i class="fas fa-paw"></i></h2>
            <div>
                <img src="img/dog_lonely.jpg" class="img-main"/>
            </div>
            <section>
                <h3 class="desc">Description</h3>
                <article>
                   <p class="description">Cet annuaire concerne uniquement les animaux perdu en Ile-de-France</p> 
                </article>
            </section>
            <section>
                <h3 class="liste">Annuaire d'organismes</h3>
                <article>
                    <div class="gauche">
                        <div class="maps">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2642.6633589387025!2d2.7166587155588515!3d48.5205177323908!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e5f0aaf07c1677%3A0x5c366ef1a0a971d9!2sLa%20Soci%C3%A9t%C3%A9%20Protectrice%20des%20Animaux%20(SPA)%20-%20refuge%20de%20Vaux-le-P%C3%A9nil!5e0!3m2!1sfr!2sfr!4v1582721699289!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                        </div>
                        <img src="img/logo_spa.jpg" class="embleme"/>
                        <p>
                            SPA refuge de Vaux-le-Pénil
                            lieu dit les Près Neufs
                            77000 Vaux-le-Pénil

                            0160565460
                        </p>
                    </div>
                </article>
            </section>
               <section>
                    <article>  
                        <div class="gauche">
                            <div class="maps">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2628.067291769868!2d1.9292165155677747!3d48.79969431279182!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e685274919be71%3A0x9e2e9a0c68e8d5fb!2sLa%20Soci%C3%A9t%C3%A9%20Protectrice%20des%20Animaux!5e0!3m2!1sfr!2sfr!4v1582721801553!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                            </div>
                            <img src="img/logo_spa.jpg" class="embleme"/>
                            <p>
                            SPA refuge de Plaisir
                            CD 134 Bois de Sainte Apolline
                            78370 Plaisir

                            0134890547
                            </p>
                        </div>
                    </article>
               </section> 
            <section>
                <article>
                    <div class="gauche">
                        <div class="maps">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d42001.93580055558!2d2.2949973837282207!3d48.85590324743066!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x2f294668ffde3dac!2sLa%20Soci%C3%A9t%C3%A9%20Protectrice%20des%20Animaux%20-%20Si%C3%A8ge%20France!5e0!3m2!1sfr!2sfr!4v1582722257980!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                        </div>
                        <img src="img/logo_spa.jpg" class="embleme"/>
                        <p>
                        SPA refuge
                        39 Boulevard Berthier
                        75017 Paris

                        0143804066
                        </p>  
                    </div>
                </article>
            </section> 
            <section>
                <article>
                    <div class="gauche">
                        <div class="maps">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2621.0690036412857!2d2.3064960155720424!3d48.93312750339574!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66f35cf77c93b%3A0x4a833ebf603296dc!2sLa%20SPA-%20refuge%20de%20Gennevilliers!5e0!3m2!1sfr!2sfr!4v1582722414254!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>   
                        </div>
                        <img src="img/logo_spa.jpg" class="embleme"/>
                        <p>
                        SPA refuge
                        30 Avenue du Général de Gaulle
                        92230 Gennevilliers
                
                        0147985740
                        </p>  
                    </div>
                </article>
            </section>
            <section>
                <article>
                    <div class="gauche">
                        <div class="maps">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2641.977306017826!2d2.207019015559299!3d48.53366663146957!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e5cfd491bee2d7%3A0x9f334a375bcd00ca!2sLa%20Soci%C3%A9t%C3%A9%20Protectrice%20des%20Animaux%20(SPA)%20-%20refuge%20de%20Chamarande!5e0!3m2!1sfr!2sfr!4v1582722472974!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                        </div>
                        <img src="img/logo_spa.jpg" class="embleme"/>
                        <p>
                        SPA refuge
                        RN20 
                        91730 Chamarande

                        0160823293
                        </p>  
                    </div>
                </article>
            </section> 
            <section>
                <article>
                    <div class="gauche">
                        <div class="maps">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10593.556568218013!2d2.6831536395771636!3d48.410673011307665!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e5f4822ed26ac7%3A0xd6771f206766d312!2sOffice%20National%20des%20Forets%20O.N.F!5e0!3m2!1sfr!2sfr!4v1582722879667!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>   
                        </div>
                        <img src="img/Logo-ONF.jpg" class="embleme"/>
                        <p>
                        Office National des Forêts
                        Boulevard de Constance
                        77300 Fontainebleau
                        
                        0160749240
                        </p>  
                    </div>
                </article>
            </section> 
            <section>
                <article>
                    <div class="gauche">
                        <div class="maps">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d21088.460992522352!2d1.821194719334198!3d48.64701282729183!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e426cb3f00c04d%3A0x284c7509c1796e0a!2sOffice%20National%20des%20For%C3%AAts!5e0!3m2!1sfr!2sfr!4v1582723716425!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                        </div>
                        <img src="img/Logo-ONF.jpg" class="embleme"/>
                        <p>
                        Office National des Forêts
                        3 Rue de Groussay
                        78120 Rambouillet

                        0130413934
                        </p>  
                    </div>
                </article>
            </section> 
            <section>
                <article>
                        <p class="aide">Vous pouvez créer une annonce pour une recherche de votre animal sur le territoire grace au site petAlert</p>
                    <div class="ligne">
                        <figure>
                        <figcaption class="sous-titre">Site officiel</figcaption>
                            <a href="https://www.petalert.fr/" class="site_aide"><img src="img/logo_pet_alert.png" class="logo_pet"/></a>
                        </figure>
                        <figure>
                        <figcaption class="sous-titre">Facebook</figcaption>
                            <a href="https://fr-fr.facebook.com/PetAlertFrance" class="site_aide"><img src="img/logo_fb.png" class="logo_pet"/></a>
                        </figure>
                    </div>
                </article>
            </section> 
            <section>
                <article>
                        <p class="aide">Vous pouvez aussi contacter l'I-CAD par email :</p>
                        <p class="aide">contact@i-cad.fr</p>
                        <div class="ligne">
                        <figure>
                        <figcaption class="sous-titre">Site officiel</figcaption>
                            <a href="https://www.i-cad.fr/" class="site_aide"><img src="img/logo_i-cad.jfif" class="logo_pet"/></a>
                        </figure>
                    </div>
                </article>
            </section> 
        </main>
    </div>