    <div>
        <main>
            <h2><i class="fas fa-paw"></i>Planning antiparasitaire<i class="fas fa-paw"></i></h2>
            <section>
                <h3>Cycle des parasites externes</h3>
                <article>
                    <img src="img/cycle-de-la-puce-chien.jpg" class="cycle">
                    <img src="img/cycle_tique.png" class="cycle">
                    <p>
                        Il est important de traiter votre animal car les parasites qu'il attrape sont transmissibles à l'homme. 
                        La contagion de ces être nuisible entraine des maladies grave comme la maladie de lyme transmise par la tique qui attaque le système nerveux.
                        La leishmaniose est une maladie de peau, elle se transmet par le phlébotome qui est un insecte qui vit dans les régions méditerranéenne.
                    </p>
                    <img src="img/phlebotme.gif" class="parasite">
                </article>
            </section>
            <section>
                <h3>Cycle des parasites internes</h3>
                <article>
                    <p>
                        Il est important de traiter votre animal car les parasites qu'il attrape sont transmissibles à l'homme. 
                        La contagion de ces être nuisibles entraine l'amaigrissement et peuvent causer des dommages à l'organisme.  
                    </p>
                    <img src="img/cycle_ascaris.jpg" class="parasite">
                </article>
            </section>
            <table>
                <h3>Calendrier de rappel antiparasitaire</h3>
                <tr>
                    <th class="attention">Printemps</th>
                    <th class="attention">Ete</th>
                    <th class="attention">Automne</th>
                    <th class="vigilance">Hiver</th>
                </tr>
                <tr>
                    <td class="attention">Début de prolifération des parasites, protégez votre animal.</td>
                    <td class="attention">Prolifération importante de parasite, protégez votre animal.</td>
                    <td class="attention">Prolifération importante de parasite, protégez votre animal.</td>
                    <td class="vigilance">Prolifération moins élevée ou faible de parasite, protégez votre animal si nécessaire en fonction du temps.</td>
                </tr>
            </table>
            <section>
                <article>
                    <h3>Conseil</h3>
                    <p>Le vermifuge s'administre tous les 3 mois pour les animaux en contact avec l'extérieur.</p>
                    <p>Les pipettes, les sprays ou les comprimés s'administrent tous les mois alors que les colliers sont efficaces pendant 5 à 6 mois contre les parasites externes.</p>
                    <p>Pensez à changer de molécule quand vous achetez vos produits antiparasitaires pour une protection optimale de votre animal.</p>
                </article>
            </section>
        </main>
    </div>