    <div>
        <main>
            <h2><i class="fas fa-paw"></i>Urgence médicale<i class="fas fa-paw"></i></h2>
            <div>
                <img src="img/veto_cat.jpg" class="img-vet"/>
            </div>
            <section>
                <h3 class="desc">Description</h3>
                <article>
                   <p class="explication">Cet annuaire concerne uniquement les animaux d'Ile-de-France</p> 
                </article>
            </section>
            <section>
                <h3 class="annuaire">Annuaire des spécialistes de santé</h3>
                <article>
                    <div class="gauche">
                        <div class="cartes">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2642.1807587623243!2d2.542304315559186!3d48.529767531742905!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e5ef61c1883c57%3A0x46f141037c8e0f95!2sClinique%20V%C3%A9t%C3%A9rinaire%20Cvet!5e0!3m2!1sfr!2sfr!4v1582630400283!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                        </div>
                        <img src="img/logo_vet.jfif" class="logo-vet"/>
                        <p>
                            Clinique Vétérinaire Cvet 
                            67 Bis av Fontainebleau
                            77310 Saint Fargeau Ponthierry
    
                            01 60 65 57 41
                        </p>
                    </div>
                </article>
            </section>
               <section>
                    <article>  
                        <div class="gauche">
                            <div class="cartes">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2627.653842692464!2d2.325369015568043!3d48.80758491223685!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6710518c99747%3A0x353cea404e22504b!2sChv%20Fregis%20SCP%20Corlouer%20Cauzinille...!5e0!3m2!1sfr!2sfr!4v1582632480775!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                            </div>
                            <img src="img/logo_hopital_fregis.png" class="logo-vet"/>
                            <p>
                                CVH Frégis
                                43, avenue Aristide Briand
                                94110 Arcueil
                                
                                01 47 35 30 69
                            </p>
                        </div>
                    </article>
               </section> 
                <section>
                    <article>
                        <div class="gauche">
                            <div class="cartes">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10510.427672235883!2d2.4211327397807345!3d48.80848040012147!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6731d6f3981f1%3A0xa2c73cb3132ba49b!2s%C3%89cole%20Nationale%20V%C3%A9t%C3%A9rinaire%20d&#39;Alfort!5e0!3m2!1sfr!2sfr!4v1582630739836!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                            </div>
                            <img src="img/logo_hopital_alfort.jpg" class="logo-vet"/>
                            <p>
                                Ecole Nationale Vétérinaire d’Alfort 
                                7 Avenue du Général de Gaulle 
                                94704 Maisons-Alfort cedex
                                
                                01 43 96 71 00 
                            </p>  
                        </div>
                    </article>
                </section>
        </main>
    </div>